apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-deposit
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-deposit
  template:
    metadata:
      labels:
        role: nfs-server-deposit
    spec:
      containers:
        - name: nfs-server
          image: gcr.io/google_containers/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /deposit
              name: nfs-deposit

      volumes:
        - name: nfs-deposit
          gcePersistentDisk:
            pdName: nfs-deposit
            fsType: ext4