version: '3.4'

services:
  genesis:
    build:
      context: ./
      target: genesis
    volumes: 
      - multinet-data:/root/multinet/repo/data

  deposits:
    build:
      context: ./
      target: deposits
    volumes: 
      - multinet-deposits:/root/multinet/repo/deposits

  nimbus:
    hostname: nimbus
    depends_on: 
      - genesis
      - deposits
    build:
      context: ./
      target: nimbus
    networks:
      mesh:
        ipv4_address: 172.20.0.10
    environment: 
      LOG_LEVEL: "INFO;TRACE:switch"
    volumes: 
      # editable source here
      - nimbus-source:/root/multinet/repo/nim-beacon-chain
      - multinet-deposits:/root/multinet/repo/deposits
      - multinet-data:/root/multinet/repo/data
    command: bash -c "./make_genesis.sh && ./run_nimbus.sh"
    
  lighthouse:
    hostname: lighthouse
    depends_on: 
      - genesis
      - deposits
    networks:
      - mesh
    build:
      context: ./
      target: lighthouse
    environment: 
      - RUST_LOG=trace,libp2p=trace,multistream=trace,gossipsub=trace
    volumes: 
      # editable source here
      - lighthouse-source:/root/multinet/repo/lighthouse
      - multinet-deposits:/root/multinet/repo/deposits
      - multinet-data:/root/multinet/repo/data
    command: bash -c "./wait_for.sh -t 0 nimbus:50000 -- ./run_lighthouse.sh"

volumes: 
  multinet-data:
  multinet-deposits:
  nimbus-source:
  lighthouse-source:

networks:
  mesh:
    ipam:
      config:
        - subnet: 172.20.0.0/24