kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: common-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      name: common-data