apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data
  labels:
    name: common-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /data/deposits
    server: 172.17.0.3