apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data
  labels:
    name: common-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /data/data
    server: nfs-server.default.svc.cluster.local