apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-data
  labels:
    name: common-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /common
    server: 10.24.229.18