apiVersion: v1
kind: PersistentVolume
metadata:
  name: deposits-storage
  labels:
    name: deposits-storage
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /
    server: nfs-server.default.svc.cluster.local