apiVersion: v1
kind: PersistentVolume
metadata:
  name: deposits-storage
  labels:
    name: deposits-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /eth20
    server: 10.80.135.178