apiVersion: v1
kind: PersistentVolume
metadata:
  name: deposits-storage
  labels:
    name: deposits-storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path: /data/data
    server: 172.17.0.2