apiVersion: v1
kind: Service
metadata:
  name: eth2stats
spec:
  type: NodePort
  selector:
    app: eth2stats-server
  ports:
    - protocol: TCP
      port: 8080
      nodePort: {{ .Values.ETH2STATS_SERVER_PORT }}
      name: api
    - protocol: TCP
      port: 9090
      name: grpc