apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  labels:
    app: multinet
    tier: lighthouse
spec:
  replicas: {{ .Values.LIGHTHOUSE_NODES }}
  serviceName: lighthouse
  selector:
    matchLabels:
      tier: lighthouse
  template:
    metadata:
      generateName: lighthouse-
      labels:
        tier: lighthouse
    spec:
      volumes:
        - name: deposits
          persistentVolumeClaim:
            claimName: deposits-storage
            readOnly: false
        - name: common-data
          persistentVolumeClaim:
            claimName: common-data
            readOnly: false
      containers:
        - name: lighthouse
          image: eth2clients/multinet-lighthouse
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /root/multinet/repo/deposits
            name: deposits
          - mountPath: /root/multinet/repo/data
            name: common-data
          command: [ "bash", "-c"]
          ports:
          - containerPort: 5052
          args:
          - ./wait_for.sh -t 0 bootstrap:50000 -- ./run_lighthouse.sh
          # inject environment variables
          env:
            - name: MULTINET_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MULTINET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: eth2stats-client
          image: eth2clients/eth2stats-client
          imagePullPolicy: IfNotPresent
          args: ["run", "--v", "--eth2stats.node-name", "$(MULTINET_POD_NAME)", "--eth2stats.addr", "eth2stats:9090", "--eth2stats.tls=false", "--beacon.type", "lighthouse", "--beacon.addr", "http://$(MULTINET_POD_IP):5052"]
          env:
            - name: MULTINET_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MULTINET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      